Import('env', 'plugins')

filmEnv = env.Clone()
if filmEnv.get('OEXRLIBDIR'):
        filmEnv.Prepend(LIBPATH=env['OEXRLIBDIR'])
if filmEnv.get('OEXRINCLUDE'):
        filmEnv.Prepend(CPPPATH=env['OEXRINCLUDE'])
if filmEnv.get('OEXRFLAGS'):
        filmEnv.Prepend(CPPFLAGS=env['OEXRFLAGS'])
if filmEnv.get('OEXRLIB'):
        filmEnv.Prepend(LIBS=env['OEXRLIB'])

plugins += filmEnv.SharedLibrary('mfilm', ['mfilm.cpp', 'cnpy.cpp'])
plugins += filmEnv.SharedLibrary('ldrfilm', ['ldrfilm.cpp'])
plugins += filmEnv.SharedLibrary('hdrfilm', ['hdrfilm.cpp'])

if ['MTS_HAS_OPENEXR', 1] in filmEnv['CPPDEFINES']:
        plugins += filmEnv.SharedLibrary('tiledhdrfilm', ['tiledhdrfilm.cpp'])

Export('plugins')
